### ISSUE TITLE
Add respawn button if player is stuck

### ISSUE THREAD

**Issue by shawwwwwwww** [XRFoundation/XREngine#3131] opened 2021-09-05 04:49 UTC

**Comment by zulqarnainhanif** [comment] 2021-12-01 07:51
@HexaField the respawn button use to hide on medium screen width if i remember correctly but I fixed it in October while revamping the UI. I have tested this on multiple screen widths the issue isn't there anymore. Can we please close this issue.

**Comment by HexaField** [comment] 2021-12-14 11:32
The respawn button (bottom left of screen) has been implemented, but currently is broken or been disabled. This needs to be fixed, and a test written to ensure it stays fixed.

**Closed** 2021-12-24 22:47 UTC
Labels: good first issue
