### ISSUE TITLE
App crash in Safari

### ISSUE THREAD

**Issue by zulqarnainhanif** [XRFoundation/XREngine#4793] opened 2022-01-14 23:16 UTC
I was testing the App on Safari Browser.
I was refreshing the /login route because i was seeing a shadow behind the white loading screen logo, I was trying to capture a screenshot for it. But came across this weird app crash. The screen turned red and after that every route i opened showed the same result.
I had to restart the sever and open up a new tab for the app to work again.

![Screenshot 2022-01-15 at 3 47 07 AM](https://user-images.githubusercontent.com/30355034/149596963-efe528fc-a006-4461-b5c6-b72299d8f278.png)

**Comment by HexaField** [comment] 2022-01-24 07:50
What version of OSX and Safari is this?

**Comment by speigg** [comment] 2022-02-09 01:39
Unable to reproduce. Safari just does strange things sometimes, and then fixes itself. Closing until we can reproduce this reliably.

**Closed by speigg** 2022-02-09 01:39 UTC
