### ISSUE TITLE
ctrl+s save hotkey does not cause editor to save

### ISSUE THREAD

**Issue by patreeceeo** [XRFoundation/XREngine#4035] opened 2021-11-10 01:32 UTC
ctrl+s save hotkey does not cause editor to save

**Comment by zulqarnainhanif** [comment] 2021-11-19 20:07
@HexaField we can close this issue since i fixed it in [PR#4125](https://github.com/XRFoundation/XREngine/pull/4125) and is duplicate of [Issue#4113](https://github.com/XRFoundation/XREngine/issues/4113)

**Closed** 2021-11-19 22:21 UTC
