### ISSUE TITLE
Push Project Modifications to Github Repo from Editor

### ISSUE THREAD

**Issue by dinomut1** [XRFoundation/XREngine#6014] opened 2022-05-09 20:31 UTC
Currently the engine doesn't have a way to push updates to a project back to its github repo. We need a way to push changes made in dev to the repo, so that when deploying to production it doesn't have missing changes.

**Comment by dinomut1** [comment] 2022-05-09 20:32
This could either be a button in admin, or automatically happens on save

**Comment by HexaField** [comment] 2022-05-09 22:27
related PR https://github.com/XRFoundation/XREngine/issues/4009

**Comment by HexaField** [comment] 2022-05-23 23:15
duplicate of https://github.com/XRFoundation/XREngine/issues/4009

**Closed by HexaField** 2022-05-23 23:15 UTC
Labels: devops
